In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.model_selection import cross_val_score

In [ ]:
pacific= pd.read_csv('/content/drive/My Drive/pacific.csv')

In [ ]:
pacific.shape

(26137, 22)

In [ ]:
pacific.describe()

In [ ]:
pacific.head()

ID                 Name  ...  High Wind SW  High Wind NW
0  EP011949              UNNAMED  ...          -999          -999
1  EP011949              UNNAMED  ...          -999          -999
2  EP011949              UNNAMED  ...          -999          -999
3  EP011949              UNNAMED  ...          -999          -999
4  EP011949              UNNAMED  ...          -999          -999

[5 rows x 22 columns]

In [ ]:
pacific.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26137 entries, 0 to 26136
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                26137 non-null  object
 1   Name              26137 non-null  object
 2   Date              26137 non-null  int64 
 3   Time              26137 non-null  int64 
 4   Event             26137 non-null  object
 5   Status            26137 non-null  object
 6   Latitude          26137 non-null  object
 7   Longitude         26137 non-null  object
 8   Maximum Wind      26137 non-null  int64 
 9   Minimum Pressure  26137 non-null  int64 
 10  Low Wind NE       26137 non-null  int64 
 11  Low Wind SE       26137 non-null  int64 
 12  Low Wind SW       26137 non-null  int64 
 13  Low Wind NW       26137 non-null  int64 
 14  Moderate Wind NE  26137 non-null  int64 
 15  Moderate Wind SE  26137 non-null  int64 
 16  Moderate Wind SW  26137 non-null  int64 
 17  Moderate Win

In [ ]:
pacific.value_counts(['Name'])

Name               
            UNNAMED    2180
           FERNANDA     318
               JOHN     295
            ESTELLE     293
             DANIEL     292
                       ... 
               WENE       6
              PILAR       5
IONE 1                    5
               MOKE       4
             TWENTY       3
Length: 267, dtype: int64

In [ ]:
pacific.isnull().sum()

In [ ]:
pacific.boxplot(figsize=(10,15))
plt.show()

In [ ]:
q1 = pacific['Low Wind NE'].quantile(.25)
q3 = pacific['Low Wind NE'].quantile(.75)
IQR = q3-q1
pacific['Low Wind NE'] = np.clip(pacific['Low Wind NE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Maximum Wind'].quantile(.25)
q3 = pacific['Maximum Wind'].quantile(.75)
IQR = q3-q1
pacific['Maximum Wind'] = np.clip(pacific['Maximum Wind'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Low Wind NE'].quantile(.25)
q3 = pacific['Low Wind NE'].quantile(.75)
IQR = q3-q1
pacific['Low Wind NE'] = np.clip(pacific['Low Wind NE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Maximum Wind'].quantile(.25)
q3 = pacific['Maximum Wind'].quantile(.75)
IQR = q3-q1
pacific['Maximum Wind'] = np.clip(pacific['Maximum Wind'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Low Wind NE'].quantile(.25)
q3 = pacific['Low Wind NE'].quantile(.75)
IQR = q3-q1
pacific['Low Wind NE'] = np.clip(pacific['Low Wind NE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Low Wind SE'].quantile(.25)
q3 = pacific['Low Wind SE'].quantile(.75)
IQR = q3-q1
pacific['Low Wind SE'] = np.clip(pacific['Low Wind SE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Low Wind SW'].quantile(.25)
q3 = pacific['Low Wind SW'].quantile(.75)
IQR = q3-q1
pacific['Low Wind SW'] = np.clip(pacific['Low Wind SW'],q1-1.5*IQR, q3+1.5*IQR)


q1 = pacific['Low Wind NW'].quantile(.25)
q3 = pacific['Low Wind NW'].quantile(.75)
IQR = q3-q1
pacific['Low Wind NW'] = np.clip(pacific['Low Wind NW'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Moderate Wind NE'].quantile(.25)
q3 = pacific['Moderate Wind NE'].quantile(.75)
IQR = q3-q1
pacific['Moderate Wind NE'] = np.clip(pacific['Moderate Wind NE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Moderate Wind SE'].quantile(.25)
q3 = pacific['Moderate Wind SE'].quantile(.75)
IQR = q3-q1
pacific['Moderate Wind SE'] = np.clip(pacific['Moderate Wind SE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Moderate Wind SW'].quantile(.25)
q3 = pacific['Moderate Wind SW'].quantile(.75)
IQR = q3-q1
pacific['Moderate Wind SW'] = np.clip(pacific['Moderate Wind SW'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['Moderate Wind NW'].quantile(.25)
q3 = pacific['Moderate Wind NW'].quantile(.75)
IQR = q3-q1
pacific['Moderate Wind NW'] = np.clip(pacific['Moderate Wind NW'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['High Wind NE'].quantile(.25)
q3 = pacific['High Wind NE'].quantile(.75)
IQR = q3-q1
pacific['High Wind NE'] = np.clip(pacific['High Wind NE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['High Wind SE'].quantile(.25)
q3 = pacific['High Wind SE'].quantile(.75)
IQR = q3-q1
pacific['High Wind SE'] = np.clip(pacific['High Wind SE'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['High Wind SW'].quantile(.25)
q3 = pacific['High Wind SW'].quantile(.75)
IQR = q3-q1
pacific['High Wind SW'] = np.clip(pacific['High Wind SW'],q1-1.5*IQR, q3+1.5*IQR)

q1 = pacific['High Wind NW'].quantile(.25)
q3 = pacific['High Wind NW'].quantile(.75)
IQR = q3-q1
pacific['High Wind NW'] = np.clip(pacific['High Wind NW'],q1-1.5*IQR, q3+1.5*IQR)


In [ ]:
pacific['Moderate Wind SW']

0       -999
1       -999
2       -999
3       -999
4       -999
        ... 
26132   -999
26133   -999
26134   -999
26135   -999
26136   -999
Name: Moderate Wind SW, Length: 26137, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
pacific['Status']=le.fit_transform(pacific['Status'])
print(pacific.head())
print(pacific['Status'].unique())

         ID                 Name  ...  High Wind SW  High Wind NW
0  EP011949              UNNAMED  ...          -999          -999
1  EP011949              UNNAMED  ...          -999          -999
2  EP011949              UNNAMED  ...          -999          -999
3  EP011949              UNNAMED  ...          -999          -999
4  EP011949              UNNAMED  ...          -999          -999

[5 rows x 22 columns]
[11  3 10  2  5  1  0  7  8  6  9  4]


In [ ]:
X= pacific[['Maximum Wind', 'Minimum Pressure', 'Low Wind NE']]
Y= pacific['Status']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.2,random_state=8)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Applying Decision Tree

In [ ]:
#call the model
from sklearn.tree import DecisionTreeClassifier
dt_model= DecisionTreeClassifier(criterion="gini", max_depth=3)
#fit the model
clf=dt_model.fit(X_train, Y_train)
#Use the fitted model for prediction on test dataset
y_predicted = clf.predict(X_test)
y_predicted_train= clf.predict(X_train)
print(y_predicted)
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(Y_train,y_predicted_train))
print(classification_report(Y_train,y_predicted_train))

[10 10  3 ... 11  3  3]
[[   0    0    0    0    0   74    0    0    0    0  100    0]
 [   0    0    0    5    0    9    0    0    0    0   94   21]
 [   0    0    4    9    0    4    0    0    0    0   45   17]
 [   0    0    0 5362    0    0    0    0    0    0    0    0]
 [   0    0    0    1    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0  587    0    0    0    0  844   27]
 [   0    0    0    0    0    0    0    0    0    0    4    0]
 [   0    0    0    0    0    0    0    0    0    0    2    0]
 [   0    0    0    0    0    0    0    0    0    0    0    5]
 [   0    0    0    3    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0  191    0    0    0    0 5409    1]
 [   0    0    1    1    0    0    0    0    0    0    0 8089]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       174
           1       0.00      0.00      0.00       129
           2       0.80      0.05      0.10        79
  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.model_selection import cross_val_score

In [ ]:
print('Accuracy for Decision Tree:', accuracy_score(Y_train, y_predicted_train))
print('f1_score for Decision Tree:', f1_score(Y_train, y_predicted_train, average='macro'))
print('recall_score for Decision Tree:', recall_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))
print('precision_score for Decision Tree:', precision_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))

Accuracy for Decision Tree: 0.9302692620402697
f1_score for Decision Tree: 0.290706827052923
recall_score for Decision Tree: 0.2848927033535374
precision_score for Decision Tree: 0.3582325638721639


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy of Test dataset for Decision Tree:', accuracy_score(Y_test, y_predicted))
print('f1_score of Test dataset for Decision Tree:', f1_score(Y_test, y_predicted, average='macro'))
print('recall_score of Test dataset for Decision Tree:', recall_score(Y_test, y_predicted,pos_label='positive',average='macro'))
print('precision_score of Test dataset for Decision Tree:', precision_score(Y_test, y_predicted,pos_label='positive',average='macro'))

Accuracy of Test dataset for Decision Tree: 0.9250191277735271
f1_score of Test dataset for Decision Tree: 0.3030240121841304
recall_score of Test dataset for Decision Tree: 0.30126520372019977
precision_score of Test dataset for Decision Tree: 0.3153796455124753


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
accuracy= accuracy_score(Y_test, y_predicted)
accuracy

0.9250191277735271

In [ ]:
import csv
with open('innovators.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["SN", "Decision Tree", accuracy_score(Y_test, y_predicted)])

In [ ]:
import csv
with open('accuracy_score.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["SN", "Model", "Score"])
    writer.writerow([1, "Decision Tree", accuracy_score(Y_test, y_predicted)])
    #writer.writerow([2, "Tim Berners-Lee", "World Wide Web"])
    #writer.writerow([3, "Guido van Rossum", "Python Programming"])

Applying Random Forest

In [ ]:
#call the model
from sklearn.ensemble import RandomForestClassifier
rf_model= RandomForestClassifier(criterion="gini", max_depth=3, random_state=0)
#fit the model
clf=rf_model.fit(X_train, Y_train)
#Use the fitted model for prediction on test dataset
y_predicted = clf.predict(X_test)
y_predicted_train= clf.predict(X_train)
print(y_predicted)
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(Y_train,y_predicted_train))
print(classification_report(Y_train,y_predicted_train))

[10 10  3 ... 11  3  3]
[[   0    0    0    0    0   73    0    0    0    0  101    0]
 [   0    0    0    5    0    0    0    0    0    0  104   20]
 [   0    0    0    9    0    4    0    0    0    0   49   17]
 [   0    0    0 5362    0    0    0    0    0    0    0    0]
 [   0    0    0    1    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0  567    0    0    0    0  865   26]
 [   0    0    0    0    0    0    0    0    0    0    4    0]
 [   0    0    0    0    0    0    0    0    0    0    2    0]
 [   0    0    0    0    0    0    0    0    0    0    0    5]
 [   0    0    0    3    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0   98    0    0    0    0 5502    1]
 [   0    0    0    1    0    0    0    0    0    0   69 8021]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       174
           1       0.00      0.00      0.00       129
           2       0.00      0.00      0.00        79
  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy for Random Forest:', accuracy_score(Y_train, y_predicted_train))
print('f1_score for Random Forest:', f1_score(Y_train, y_predicted_train, average='macro'))
print('recall_score for Random Forest:', recall_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))
print('precision_score for Random Forest:', precision_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))

Accuracy for Random Forest: 0.9303170883351667
f1_score for Random Forest: 0.28332900274952966
recall_score for Random Forest: 0.28021349046667005
precision_score for Random Forest: 0.29781462839984424


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy of Test dataset for Random Forest:', accuracy_score(Y_test, y_predicted))
print('f1_score of Test dataset for Random Forest:', f1_score(Y_test, y_predicted, average='macro'))
print('recall_score of Test dataset for Random Forest:', recall_score(Y_test, y_predicted,pos_label='positive',average='macro'))
print('precision_score of Test dataset for Random Forest:', precision_score(Y_test, y_predicted,pos_label='positive',average='macro'))

Accuracy of Test dataset for Random Forest: 0.9240627390971691
f1_score of Test dataset for Random Forest: 0.30278392651091274
recall_score of Test dataset for Random Forest: 0.29999996914613136
precision_score of Test dataset for Random Forest: 0.32532648698708644


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Applying Naive Baye's

In [ ]:
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(X_train, Y_train)

#Predict the response for test dataset
y_predicted = gnb.predict(X_test)
y_predicted_train = gnb.predict(X_train)

In [ ]:
print('Accuracy for Naive Bayes:', accuracy_score(Y_train, y_predicted_train))
print('f1_score for Naive Bayes:', f1_score(Y_train, y_predicted_train, average='macro'))
print('recall_score for Naive Bayes:', recall_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))
print('precision_score for Naive Bayes:', precision_score(Y_train, y_predicted_train,pos_label='positive',average='macro'))

Accuracy for Naive Bayes: 0.8349036300157827
f1_score for Naive Bayes: 0.34216273461317104
recall_score for Naive Bayes: 0.4771432242652158
precision_score for Naive Bayes: 0.3782073956418555


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy of Test dataset for Naive Bayes:', accuracy_score(Y_test, y_predicted))
print('f1_score of Test dataset for Naive Bayes:', f1_score(Y_test, y_predicted, average='macro'))
print('recall_score of Test dataset for Naive Bayes:', recall_score(Y_test, y_predicted,pos_label='positive',average='macro'))
print('precision_score of Test dataset for Naive Bayes:', precision_score(Y_test, y_predicted,pos_label='positive',average='macro'))

Accuracy of Test dataset for Naive Bayes: 0.8333970925784239
f1_score of Test dataset for Naive Bayes: 0.2958095056701854
recall_score of Test dataset for Naive Bayes: 0.42496324633125604
precision_score of Test dataset for Naive Bayes: 0.31966726264222256


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Applying Support Vector Classification

In [ ]:
from sklearn import svm
#calling the model
clf= svm.SVC(kernel='rbf', degree=2)
#fitting the model
clf.fit(X_train,Y_train)
#Predicct the model
y_predicted= clf.predict(X_test)
y_predicted_train= clf.predict(X_train)
print(y_predicted)
print(y_predicted_train)

[10 10  3 ... 11 11  3]
[10 10 10 ... 11 10  3]


In [ ]:
print('Accuracy for SVC:', accuracy_score(Y_train, y_predicted_train))
print('f1_score for SVC:', f1_score(Y_train, y_predicted_train, average='macro'))
print('recall_score for SVC:', recall_score(Y_train, y_predicted_train, average='macro'))
print('precision_score for SVC:', precision_score(Y_train, y_predicted_train, average='macro'))

Accuracy for SVC: 0.8255296762159835
f1_score for SVC: 0.21534786037140227
recall_score for SVC: 0.22303931632611732
precision_score for SVC: 0.20970568668245257


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy of Test dataset for SVC:', accuracy_score(Y_test, y_predicted))
print('f1_score of Test dataset for SVC:', f1_score(Y_test, y_predicted, average='macro'))
print('recall_score of Test dataset for SVC:', recall_score(Y_test, y_predicted,pos_label='positive',average='macro'))
print('precision_score of Test dataset for SVC:', precision_score(Y_test, y_predicted,pos_label='positive',average='macro'))

In [ ]:
cv_svc= cross_validate(clf,X, Y)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


In [ ]:
cv_svc

{'fit_time': array([14.63001966, 13.7687366 , 13.5911119 , 15.41769838, 13.05331969]),
 'score_time': array([4.02816272, 3.72825456, 3.90384555, 4.21962309, 3.86597681]),
 'test_score': array([0.63733741, 0.65589135, 0.68815764, 0.75186531, 0.6916013 ])}

In [ ]:
from sklearn.model_selection import cross_val_score,StratifiedKFold
cv = StratifiedKFold(10)
score=cross_val_score(dt_model, X_train, Y_train, cv=cv)
print(f'score of random forest classifier:{score.mean()}')
score=cross_val_score(rf_model, X_train, Y_train, cv=cv)
print(f'score of decision tree classifier:{score.mean()}')
score=cross_val_score(clf, X_train, Y_train, cv=cv)
print(f'score of Support Vector classifier:{score.mean()}')
score=cross_val_score(gnb, X_train, Y_train, cv=cv)
print(f'score of Naive Bayes:{score.mean()}')

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


score of random forest classifier:0.9302215235493193
score of decision tree classifier:0.930412842462227


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)


score of Support Vector classifier:0.6875510218091204
score of Naive Bayes:0.8309341241456322


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
